[project]
name = "fluxbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "discord-py>=2.6.4",
    "dotenv>=0.9.9",
    "pillow>=11.3.0",
    "requests>=2.32.5",
]
